# Name of the site set, you can use your composer package name, but this is not mandatory
name: vendorname/sitepackage

dependencies:
  - typo3/fluid-styled-content
  - typo3/seo-sitemap
  - typo3/form
