categories:
  sitepackage: ~
  sitepackage.templates:
    parent: sitepackage
  sitepackage.meta:
    parent: sitepackage

settings:
  page.view.layoutRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.view.partialRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.view.templateRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.meta.viewport:
    type: string
    default: 'width=device-width, initial-scale=1, minimum-scale=1, shrink-to-fit=no'
    category: sitepackage.meta
  page.meta.robots:
    type: string
    default: 'index,follow'
    category: sitepackage.meta
  page.meta.apple-mobile-web-app-capable:
    type: string
    default: 'no'
    category: sitepackage.meta
  page.meta.compatible:
    type: string
    default: 'IE=edge,chrome=1'
    category: sitepackage.meta
  page.meta.google:
    type: string
    default: 'notranslate'
    category: sitepackage.meta
  page.meta.google-site-verification:
    type: string
    default: ''
    category: sitepackage.meta
  page.meta.apple-mobile-web-app-title:
    type: string
    default: 'Sitepackage'
    category: sitepackage.meta
