# Settings for EXT:fluid_styled_content
styles:
  templates:
    templateRootPath: 'EXT:sitepackage/Resources/Private/Templates/ContentElements/'
    partialRootPath: 'EXT:sitepackage/Resources/Private/Partials/ContentElements/'
    layoutRootPath: 'EXT:sitepackage/Resources/Private/Layouts/ContentElements/'

# Settings for EXT:seo
seo:
  sitemap:
    pages:
      additionalWhere: ' {#no_index} = 0 AND {#canonical_link} = "" AND {#sitemap_priority} > 0'

module:
  # Settings for EXT:form
  tx_form:
    settings:
      yamlConfigurations:
        100: 'EXT:sitepackage/Configuration/Form/CustomFormSetup.yaml'

plugin:
  # Settings for EXT:form
  tx_form:
    settings:
      yamlConfigurations:
        # register your own additional configuration
        # choose a number higher than 10 (10 is reserved)
        100: 'EXT:sitepackage/Configuration/Form/CustomFormSetup.yaml'
