settings:
  page.fluidtemplate.layoutRootPath:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.fluidtemplate.layoutRootPath'
    type: string
    default: ''
  page.fluidtemplate.partialRootPath:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.fluidtemplate.partialRootPath'
    type: string
    default: ''
  page.fluidtemplate.templateRootPath:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.fluidtemplate.templateRootPath'
    type: string
    default: ''
  page.meta.viewport:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.viewport'
    type: string
    default: 'width=device-width, initial-scale=1, minimum-scale=1, shrink-to-fit=no'
  page.meta.robots:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.robots'
    type: string
    default: 'index,follow'
  page.meta.apple-mobile-web-app-capable:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.apple-mobile-web-app-capable'
    type: string
    default: 'no'
  page.meta.compatible:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.compatible'
    type: string
    default: 'IE=edge,chrome=1'
  page.meta.google:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.google'
    type: string
    default: 'notranslate'
  page.meta.google-site-verification:
    label: 'LLL:EXT:sitepackage/Resources/Private/Language/locallang_be.xlf:constants.page.meta.google-site-verification'
    type: string
    default: ''