categories:
  sitepackage: ~
  sitepackage.templates:
    parent: sitepackage
  sitepackage.meta:
    parent: sitepackage
  sitepackage.webmanifest:
    parent: sitepackage

settings:
  page.view.layoutRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.view.partialRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.view.templateRootPath:
    type: string
    default: ''
    category: sitepackage.templates
  page.meta.viewport:
    type: string
    default: 'width=device-width, initial-scale=1, minimum-scale=1, shrink-to-fit=no'
    category: sitepackage.meta
  page.meta.robots:
    type: string
    default: 'index,follow'
    category: sitepackage.meta
  page.meta.apple-mobile-web-app-capable:
    type: string
    default: 'no'
    category: sitepackage.meta
  page.meta.compatible:
    type: string
    default: 'IE=edge,chrome=1'
    category: sitepackage.meta
  page.meta.google:
    type: string
    default: 'notranslate'
    category: sitepackage.meta
  page.meta.google-site-verification:
    type: string
    default: ''
    category: sitepackage.meta
  page.meta.apple-mobile-web-app-title:
    type: string
    default: 'Sitepackage'
    category: sitepackage.meta
  page.webmanifest.name:
    type: string
    default: 'TYPO3 Sitepackage'
    category: sitepackage.webmanifest
  page.webmanifest.short_name:
    type: string
    default: 'Sitepackage'
    category: sitepackage.webmanifest
  page.webmanifest.icons.sizes:
    type: stringlist
    default:
      - 192x192
      - 512x512
    category: sitepackage.webmanifest
  page.webmanifest.icons.file.prefix:
    type: string
    default: 'web-app-manifest-'
    category: sitepackage.webmanifest
  page.webmanifest.icons.file.type:
    type: string
    default: 'png'
    category: sitepackage.webmanifest
    enum:
      'apng': 'Animated Portable Network Graphics (APNG) image'
      'avif': 'Archive document (multiple files embedded)'
      'bmp': 'Windows OS/2 Bitmap Graphics'
      'gif': 'Graphics Interchange Format (GIF)'
      'ico': 'Icon format'
      'jpg': 'JPEG images'
      'png': 'Portable Network Graphics'
      'svg': 'Scalable Vector Graphics (SVG)'
      'tif': 'Tagged Image File Format (TIFF)'
      'webp': 'WEBP image'
  page.webmanifest.icons.file.purpose:
    type: string
    default: 'maskable'
    category: sitepackage.webmanifest
    enum:
      'maskable': 'Maskable'
      'monochrome': 'Monochrome'
      'any': 'Any'
  page.webmanifest.theme_color:
    type: color
    default: '#ffffff'
    category: sitepackage.webmanifest
  page.webmanifest.background_color:
    type: color
    default: '#ffffff'
    category: sitepackage.webmanifest
  page.webmanifest.display:
    type: string
    default: 'standalone'
    category: sitepackage.webmanifest
    enum:
      'fullscreen': 'Fullscreen'
      'standalone': 'Standalone'
      'minimal-ui': 'Minimal UI'
      'browser': 'Browser'
