# https://docs.typo3.org/c/typo3/cms-rte-ckeditor/11.5/en-us/Configuration/Reference.html

imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config

editor:
  config:
    contentsCss:
      - 'EXT:rte_ckeditor/Resources/Public/Css/contents.css'
      - 'EXT:sitepackage/Resources/Public/Css/rte.css'
