# https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Yaml/ServicesYaml.html

services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VendorName\Sitepackage\:
    resource: '../Classes/*'
