# https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/Configuration/Yaml/ServicesYaml.html

services:
  # https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/DependencyInjection/Index.html#id7
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VendorName\Sitepackage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/CommandControllers/Tutorial.html#register-the-command
  VendorName\Sitepackage\Command\DoSomethingCommand:
    tags:
      - name: console.command
        command: 'sitepackage:dosomething'
        description: 'A command that does nothing and always succeeds.'