# https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/Configuration/Yaml/ServicesYaml.html

services:
  # https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/DependencyInjection/Index.html#id7
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VendorName\Sitepackage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
